name: Sync and Build Tasklogger

on:
  push:
    branches:
      - master  # Ou o branch que você deseja observar
    paths:
      - 'android/src/main/java/com/phonereplay/phone_replay_flutter_lib/tasklogger/**'
  workflow_dispatch:

jobs:
  sync-and-build-tasklogger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout phone-replay-flutter-lib repository
        uses: actions/checkout@v2

      - name: Clone android-core-flutter repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git clone https://phone-replay:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/phone-replay/android-core-flutter.git
          cd android-core-flutter
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Copy tasklogger to android-core-flutter repository
        run: |
          cp -r android/src/main/java/com/phonereplay/phone_replay_flutter_lib/tasklogger android-core-flutter/phone-replay/src/main/java/com/phonereplay/phone_replay_flutter_lib/
          cd android-core-flutter
          git add .
          git commit -m "Update tasklogger with latest changes from phone-replay-flutter-lib"

      - name: Push changes to android-core-flutter repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cd android-core-flutter
          git push origin HEAD:master  # Substitua 'main' pelo nome do branch correto do android-core-flutter

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build the project
        run: |
          cd android-core-flutter
          ./gradlew clean assembleRelease  # Altere conforme necessário para o seu projeto

      - name: Move .aar to project root
        run: |
          mv android-core-flutter/app/build/outputs/aar/app-release.aar android-core-flutter/app-release.aar

      - name: Upload .aar artifact
        uses: actions/upload-artifact@v2
        with:
          name: phone-replay-flutter-lib.aar
          path: android-core-flutter/app-release.aar  # Caminho atualizado para a raiz do projeto
